### ISSUE TITLE
DataTables Ajax error & 500 (internal server error)

### ISSUE THREAD

**Issue by Atif-Farooq** [abedputra/Attendance-login-system#10]
![DataTables Ajax error 500 (internal server error)](https://user-images.githubusercontent.com/71881335/94273905-74372080-ff5e-11ea-8542-42628ce3285f.jpg)

Dear Abed,
Can you help me in your project (Attendance Login System) I'm having this issue to creating users plz look into this matter.
find attached picture.

**Comment by abedputra** [comment]
Hi,

Thanks for the report.

have you tried `composer update`?

**Comment by abedputra** [comment]
Please try `composer install` and then `composer update`.

Thanks

**Comment by Atif-Farooq** [comment]
![AjaxDataTables warning table id - Ajax error](https://user-images.githubusercontent.com/71881335/94332385-384b9c00-ffee-11ea-96c9-eef0923affae.jpg)
![composer 2 0 0-RC1](https://user-images.githubusercontent.com/71881335/94332386-3a155f80-ffee-11ea-8b9b-a558216503aa.png)



Hi,
yes I installed `composer install` and then `composer update` to `-v` newer version  Composer version 2.0.0-RC1 2020-09-10

and after that I'm also getting that error DataTables Ajax error & 500 (internal server error)

**Comment by Atif-Farooq** [comment]
plz see my **Directories** to check and confirm if my **project** locations are **correct**? 

composer installed in         >    C:\ProgramData\ComposerSetup\bin

Attendance Login System   >   C:\xampp\htdocs\attendance\index.php

**Comment by abedputra** [comment]
Please open the folder where the system installed, and type composer install. 

The system need install requirements like datatables. 

Thanks

**Comment by Atif-Farooq** [comment]
Thanks Bro. Its Working Now!...

**Comment by ghandour87** [comment]
> Thanks Bro. Its Working 

> Thanks Bro. Its Working Now!...

Hello.  Can you help me?. How did you fix your ajax error. I followed all the required in #10 ,but still the message appears

**Comment by Atif-Farooq** [comment]
> > Thanks Bro. Its Working Now!...
> 
> Hello. Can you help me?. How did you fix your ajax error. I followed all the required in #10 ,but still the message appears

ghandour87 plz show us your code where you have message errors..

**Comment by ghandour87** [comment]
> Thanks Bro. Its Working Now!...

hello , after installing this script using localhost an error alert : DataTables warning: table id=data-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7.
how can i fix it? specially when adding new user since this error prevents me to add a new employee.
using WAMP server , PHP 7.2

I followed all what abed told you in #10

I sent screen shots to abed in ticket #13.  Big thanks for you help

https://user-images.githubusercontent.com/75255410/100671234-ce8e9c00-3368-11eb-8f79-1f479e6665fc.png

https://user-images.githubusercontent.com/75255410/100671270-dd754e80-3368-11eb-8144-a93b00feca4a.png

https://user-images.githubusercontent.com/75255410/100671266-da7a5e00-3368-11eb-9085-6aed3ada4990.png

**Comment by Atif-Farooq** [comment]
> > Thanks Bro. Its Working Now!...
> 
where you installed the Attendance login system files?

**Comment by ghandour87** [comment]
Installing in:  C/wamp64/www/attendance

**Comment by Atif-Farooq** [comment]
C:\xampp\htdocs\attendance 

so in attendance root dirrectory open cmd and hit `composer install`

**Comment by ghandour87** [comment]
Thanks alot dear. My full best thanks for your help

**Comment by Atif-Farooq** [comment]
My Pleasure dear.
