### ISSUE TITLE
Dashboard Issue

### ISSUE THREAD

**Issue by glenn6452** [abedputra/Attendance-login-system#4]
Hi I test this system. And now I'm seeing the reverse of the data. It shows 5 absent today even it's 5 are present. What to do with this?

**Comment by abedputra** [comment]
Hi,
Sorry, I don't understand...what do you mean?

Best Regards,

Abed Putra
Full Stack Developer
http://abedputra.com

**Comment by glenn6452** [comment]
What do you mean on Absent on this system? Because it should show Person Present Today. Instead of Person Absent Today. How should I fix that?
![image](https://user-images.githubusercontent.com/22776846/49337249-6c044780-f64b-11e8-8b09-c8355a03cf4e.png)

**Comment by abedputra** [comment]
its mean, count how many your employees attendance today.

if you want change it, please check this page
https://github.com/abedputra/Attendance-login-system/blob/master/application/views/index.php

thanks

**Comment by drbeanz** [comment]
Hello sir. I am not seeing a reflection of the clock in and out via qr the admin dash still says 0% absent and 0% present today help plz

**Comment by drbeanz** [comment]
The app load well and I was able to log in and i downloaded the app from the play store and set the key and http://10.0.0.21/attendance. I scan barcode successfully but the dash board shows nothing about who clock in nor out and is not loaded in the database...just want to be clear so u can assist...thanks much

**Comment by abedputra** [comment]
After scan, what message did you get?
If message said success its mean the data already saved, and you can see the details of data, including the time.
Also please check the DB, is it your data saved as well...
Thanks

**Comment by drbeanz** [comment]
Hello Sir i dont see anything in the absent database.......and the message is blank...

**Comment by drbeanz** [comment]
in the qr setting i use 10.0.0.21/attendance is there a specific folder to navigate to? I am sure the key is correct my only issue is that the absent and token fields are not populated......everything else is ok..

**Comment by drbeanz** [comment]
Rhe app was the issue on my phone....others were able to clock in but I
realised I could clock in as many time as I want and it adds to the
employee count is there a way to let the count remain if it's the same
person?

On Jan 7, 2019 19:18, "Abed Putra" <notifications@github.com> wrote:

After scan, what message did you get?
If message said success its mean the data already saved, and you can see
the details of data, including the time.
Also please check the DB, is it your data saved as well...
Thanks

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/abedputra/Attendance-login-system/issues/4#issuecomment-452129484>,
or mute the thread

**Comment by abedputra** [comment]
To fill the url like this
Ex: yourl url is http://yoururl.com/ and inside your url has a folder , for example "employeeqr" so the url is http://yoururl.com/employeeqr/

The deference pro and free is, the pro has no ads, and free has ads just it.

Thanks

**Comment by drbeanz** [comment]
Hello there,

I just signed the petition "Prime Minister Andrew Holness and every Member
of the Jamaican Parliament: No to Conscience Vote! No to Legalizing
Abortion in Jamaica!" and wanted to see if you could help by adding your
name.

Our goal is to reach 5,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/6cyX2cxv4T

Thanks!
Jerome
